### ISSUE TITLE
Node-Red crashes when try to connect with keycloack with selfsigned certs

### ISSUE THREAD

**Issue by Nxito** [ncarlier/node-red-contrib-auth-oidc#2]
Hi,  im trying to connect this node to keycloack and node-red crashes

first i try with http, but  i see a error msg in the console

then y try https with selfsigned certs and node-red crashes with this message in the logs : 

```
6 Oct 10:54:22 - [info] Starting flows
6 Oct 10:54:23 - [info] Started flows
6 Oct 10:54:23 - [red] Uncaught Exception:
6 Oct 10:54:23 - Error: self signed certificate
at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
at TLSSocket.emit (events.js:315:20)
at TLSSocket._finishInit (_tls_wrap.js:932:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
6 Oct 10:54:24 - [info]
```

i tried to ignore selfsigned from nodejs and stop crashing, but still failing
```

`6 Oct 08:49:20 - [info] Starting flows

(node:18) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

(Use `node --trace-warnings ...` to show where the warning was created)

6 Oct 08:49:20 - [info] Started flows

JWKS URI: "https://keycloak:8443/auth/realms/nodered/protocol/openid-connect/certs"

6 Oct 08:49:58 - [error] [auth-oidc:a71de9971dcb5074] Access token not found in the request`
```
any idea why?

**Comment by ncarlier** [comment]
Hi, this message means that you are not providing access token to the endpoint (with HTTP header: `Authorization: Bearer XXX`).
First you have to obtain the token from Keycloak (regarding your client and flow type). Then put the access token inside the authorization header of your HTTP request. Finally this node will validate the Token.
